name: feed & train camel

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Feed and train 🐪
        uses: danthelion/tc-feeder@0.3
        env:
          TC_USER: ${{ secrets.TC_USER }}
          TC_PASSWORD: ${{ secrets.TC_PASSWORD }}
